name: Panorama on Azure Workflow
label: Panorama on Azure
description: |
  Panorama on Azure Workflow

type: workflow

labels:
  collection:
    - Azure Reference Architecture Azure Skillets

snippets:
  - name: Panorama on Azure
  - name: Capture Output for IP in Azure
  - name: Configure Panorama on Azure
