name: Capture Output for IP on GCP

label: 2 - Capture Panorama IP

description: |
  Capture the Panorama IP details from Terraform so following steps have the information available

type: python3

labels:
  order: 2
  collection:
    - GCP Reference Architecture Skillet Modules

# These two hidden variables are passed to the Python script and ultimately to Terraform
variables:
  - name: GOOGLE_CREDENTIALS
    description: GCP Credentials
    default: ""
    type_hint: hidden

# This uses output capturing to get values from the output and set them in the users session. Each subsequent skillet
# will have access to the captured_username and captured_secret variables from below.
snippets:
  - name: script
    file: output_capture.py
    input_type: env
    output_type: json
    outputs:
      - name: Panorama_IP
        capture_pattern: 'Primary_IP'
      - name: Secondary_IP
        capture_pattern: 'Secondary_IP'
      - name: Primary_Private_IP
        capture_pattern: 'Primary_Private_IP'
      - name: Secondary_Private_IP
        capture_pattern: 'Secondary_Private_IP'
