---
- name: Commit
  hosts: primary-panorama
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
  - name: Commit candidate configuration
    panos_commit:
      provider:
        ip_address: '{{ ip_address }}'
        password: '{{ password }}'