name: Inbound AppGw on Azure

label: Deploy Azure Inbound Security with an Application Gateway

description: |
  Deploy Inbound security with an AppGW in the Azure Transit VNet Design Model

type: python3

labels:
  collection:
    - Azure Reference Architecture Skillet Modules

variables:
  - name: DEPLOYMENT_NAME
    description: Prefix for deployment
    default: ""
    type_hint: hidden
  - name: PASSWORD
    description: Password for the admin account
    default:
    type_hint: hidden
  - name: Panorama_IP
    description: Panorama IP
    default:
    type_hint: hidden
  - name: authcode
    description: Authcode for the VM-Series firewall license
    type_hint: text
  - name: Init
    description: Deploy or destroy the environment
    default: ip_address
    type_hint: dropdown
    dd_list:
      - key: 'Deploy'
        value: "apply"
      - key: 'Destroy'
        value: 'destroy'

snippets:
  - name: script
    file: deploy_appgw.py
    input_type: env



